### ISSUE TITLE
MM Minimap Type changes needed

### ISSUE THREAD

**Issue by mzxrules** [NEstelami/ZAPD#254]
Still in the middle of decomping things, but here's what I have so far

```
typedef struct {
    /* 0x00 */ u16 unk0;
    /* 0x02 */ s16 unk2;
    /* 0x04 */ UNK_TYPE2 unk4;
    /* 0x06 */ s16 unk6;
    /* 0x08 */ u16 unk8;
} MinimapEntry; // size = 0xA

typedef struct {
    /* 0x00 */ MinimapEntry* entry;
    /* 0x04 */ s16 unk4;  // <-- currently extracted as s32. 0x06 could be padding but I haven't actually checked the data
} MinimapList; // size  = 0x8

typedef struct {
    /* 0x00 */ UNK_TYPE2 unk0;
    /* 0x02 */ UNK_TYPE2 unk2;
    /* 0x04 */ UNK_TYPE2 unk4;
    /* 0x06 */ UNK_TYPE2 unk6;
    /* 0x08 */ UNK_TYPE2 unk8;
} MinimapChest; // size = 0xA
```

**Comment by AngheloAlf** [comment]
Just checked every scene and seems like `unk06` is always zero, so it is very likely to just be padding.
This will be annoying to fix, because we well need to first introduce and merge a new struct that will replace this one while keeping the old wrong one before being able to fix this problem on ZAPD's side, otherwise fixing this here won't match

**Comment by mzxrules** [comment]
happy new year everyone
